### ISSUE TITLE
ImportError for pairtools

### ISSUE THREAD

**Issue by jawmest101** [XiaoTaoWang/HiC_pipeline#10]
Hi XiaoTao,
I have encountered an error in running runHiC at very beginning. The program was stopped very quickly after running the following command:
`runHiC mapping -p ~/bio/tools/runHiC/data/ -g tair10 -f HiC_CL -F FASTQ -A bwa-mem -t 10 --include-readid --drop-seq --chunkSize 1500000 --logFile runHiC-mapping.log`

then, I check the log file and it gives me information as below: 

```
root                 main    @ 12/05/22 21:21:46: 
# ARGUMENT LIST:
# Sub-Command Name = mapping
# MetaData = datasets.tsv
# Data Root Folder = /home/alexchen/bio/tools/runHiC/data
# Genome Name = tair10
# Chromsome Sizes = None
# Sequencing Data Folder = HiC_CL
# Sequencing Format = FASTQ
# Alignment Software = bwa-mem
# Genome Index = None
# Mapping Threads = 10
# Minimal MAPQ = 1
# Maximal Molecule Size = 2000
# Max Inter Align Gap = 20
# Walks Policy = all
# Include Read ID = True
# Include Sam = False
# Drop SEQ and QUAL = True
# Add Restriction Fragment = False
# Memory for sort = 8G
# Chunk size = 1500000
# Temporary Dir = .runHiC
Traceback (most recent call last):
  File "/home/alexchen/anaconda3/envs/runHiC/bin/runHiC", line 834, in <module>
    run(args, commands)
  File "/home/alexchen/anaconda3/envs/runHiC/bin/runHiC", line 284, in run
    args.func(args, commands)
  File "/home/alexchen/anaconda3/envs/runHiC/bin/runHiC", line 288, in mapping
    from runHiC.mapping import splitSRA, splitSingleFastq, uncompressSRA, buildMapIndex, map_core, parse_align
  File "/home/alexchen/anaconda3/envs/runHiC/lib/python3.7/site-packages/runHiC/mapping.py", line 9, in <module>
    from pairtools import _fileio, _headerops
ImportError: cannot import name '_fileio' from 'pairtools'  (/home/alexchen/anaconda3/envs/runHiC/lib/python3.7/site-packages/pairtools/__init__.py)
```

My pairtools version is pairtools-1.0.2. Could you help me to solve the issue? 

Thanks

**Comment by XiaoTaoWang** [comment]
Hi, sorry for the delay. I just noticed that the developers of pairtools introduced huge changes since 1.0.0 (https://github.com/open2c/pairtools/blob/master/CHANGES.md). It might take me some time to make runHiC and potentially my other softwares compatible with new pairtools, so at this moment, can you downgrade your pairools to the version 0.3.0, and try again?

**Comment by XiaoTaoWang** [comment]
@jawmest101 I have made the program compatible with the latest pairtools version. Can you upgrade your runHiC to 0.8.7 and try again? Thanks!

**Comment by nzx9581** [comment]
> @jawmest101 I have made the program compatible with the latest pairtools version. Can you upgrade your runHiC to 0.8.7 and try again? Thanks!

Hello, developer

Now we have newest version of runHiC (v 0.8.7) and new pairtools (1.0.3), but we still get the same error with [jawmest101](https://github.com/jawmest101). Could you please help us to solve the problem? Thank you so much.

**Comment by XiaoTaoWang** [comment]
Hi, this is strange to me. Could you open a Python interpreter, execute the following commands, and let me know if the same error occurred? Thanks!

    >>> from pairtools.lib import fileio
    >>> from pairtools.lib import headerops

**Comment by nzx9581** [comment]
Hi, I ran these two commands you gave me. But nothing happened, it works well.

**Comment by XiaoTaoWang** [comment]
Double check the version of runHiC you previously ran is 0.8.7?

**Comment by PinpinSui** [comment]
Hi Xiaotao,

Thank you so much for this tools!

I just install runHiC (v 0.8.7) with pairtools v(1.0.2).  I can run "from pairtools.lib import fileio" normally. But when I run runHiC mapping, I get the following error:
ImportError: cannot import name 'dedup_cython' from partially initialized module 'pairtools.lib' (most likely due to a circular import)

Can you help me take a look?

Thank you,

Pinpin

**Comment by XiaoTaoWang** [comment]
Hi Pinpin,

Can you downgrade your pairtools to v0.3?

Xiaotao

**Comment by PinpinSui** [comment]
Hi Xiaotao,

it works well after downgrate paritools to v0.3.

Thank you so much!

Pinpin

**Comment by PinpinSui** [comment]
Hi Xiaotao,
Thank you so much for this wonderful tool. I got mcool file smmoothly!
Best,
Pinpin
