### ISSUE TITLE
Error when filtering reads:

### ISSUE THREAD

**Issue by oriolfornes** [XiaoTaoWang/HiC_pipeline#4]
Hi, I have run the pipeline successfully for a few datasets. For others, however, the pipeline breaks during the filtering step.

Here is an example dataset that fails for me:
- SRAs: `SRR1501142 SRR1501143 SRR1501144 SRR1501145 SRR1501146`
- Sample: `left ventricle`
- Enzyme: `HindIII`
- Metadata file:
```
SRR1501142	cf195000156b184c7e6bfbcb3848535d	R1	HindIII
SRR1501143	cf195000156b184c7e6bfbcb3848535d	R1	HindIII
SRR1501144	cf195000156b184c7e6bfbcb3848535d	R1	HindIII
SRR1501145	cf195000156b184c7e6bfbcb3848535d	R1	HindIII
SRR1501146	cf195000156b184c7e6bfbcb3848535d	R1	HindIII
```
- Error:
```
$ cat cf195000156b184c7e6bfbcb3848535d/hi-c/runHiC-filtering.log 
root                 main    @ 06/02/19 16:27:46: 
# ARGUMENT LIST:
# Sub-Command Name = filtering
# Original Pairs = ./pairs-hg19/
# MetaData = ./metadata.tsv
# Genome Path = /sp3work/oriol/Hi-C/cf195000156b184c7e6bfbcb3848535d/data/hg19/hg19.fa
# Stats Cache = allinone.cache
# Temporary Dir = /sp1work/tmp/
root                 main    @ 06/02/19 16:27:49: Filtered files will be saved under /sp3work/oriol/Hi-C/cf195000156b184c7e6bfbcb3848535d/hi-c/filtered-hg19
root                 main    @ 06/02/19 16:27:49: Merge chunks ...
root                 main    @ 06/02/19 16:27:49: Current SRA/FASTQ: SRR1501142 ...
root                 main    @ 06/02/19 17:10:18: Done
root                 main    @ 06/02/19 17:10:18: Current SRA/FASTQ: SRR1501143 ...
root                 main    @ 06/02/19 17:54:18: Done
root                 main    @ 06/02/19 17:54:18: Current SRA/FASTQ: SRR1501144 ...
root                 main    @ 06/02/19 18:37:34: Done
root                 main    @ 06/02/19 18:37:34: Current SRA/FASTQ: SRR1501145 ...
root                 main    @ 06/02/19 19:19:29: Done
root                 main    @ 06/02/19 19:19:29: Current SRA/FASTQ: SRR1501146 ...
Traceback (most recent call last):
  File "/home/oriol/.conda/envs/tadpy/bin/runHiC", line 811, in <module>
    run(args, commands)
  File "/home/oriol/.conda/envs/tadpy/bin/runHiC", line 284, in run
    args.func(args, commands)
  File "/home/oriol/.conda/envs/tadpy/bin/runHiC", line 572, in filtering
    stats = collect_stats(inFiles)
  File "/home/oriol/.conda/envs/tadpy/lib/python3.6/site-packages/runHiC/filtering.py", line 32, in collect_stats
    merge_stats(stats_pool, list(stats_pool.keys()), 'pseudo')
  File "/home/oriol/.conda/envs/tadpy/lib/python3.6/site-packages/runHiC/filtering.py", line 161, in merge_stats
    stats_pool[outkey][i] += stats_pool[k][i]
KeyError: '124_DanglingReads'
```
- Python:
```
$ python --version
Python 3.6.7
```

Thank you in advance!

**Comment by XiaoTaoWang** [comment]
Hi,

Thanks for your feedback! This is probably a bug for datasets with low sequencing depth, in which case not all SRAs can be detected with dangling reads. Can you try the latest version 0.8.3.post1 (https://pypi.org/project/runHiC/)?

Best!

**Comment by oriolfornes** [comment]
Updating to 0.8.3.post1 worked, thank you. I also wanted to thank you for your other great tools. Together, runHiC and TADLib are a powerful resource!
