### ISSUE TITLE
Space in the directory 

### ISSUE THREAD

**Issue by zuoyi93** [XiaoTaoWang/HiC_pipeline#7]
Dear Dr. Wang,

Thanks for making the awesome `HiC` tutorial! However, I experienced an error while running it. I believe it's due to the space in the directory. 

Specifically, when I ran the following code,

```
runHiC mapping -p ../data/ -g hg38 -f HiC-SRA -F SRA -A bwa-mem -t 10 -O BAM --include-readid --include-sam --drop-seq --chunkSize 1500000 --logFile runHiC-mapping.log
```

it gave me the following error:

```
[bwa_idx_build] fail to open file '/Users/Buzzzuoyi/Google' : No such file or directory
```

I noticed the following information in the log:

```
# Data Root Folder = /Users/Buzzzuoyi/Google Drive/learn/data

root                 main    @ 07/17/21 20:45:19: Chromosome sizes are not provided, attempt to fetch from fasta reference genome ...
root                 main    @ 07/17/21 20:45:44: Done
root                 main    @ 07/17/21 20:45:44: You didn't specify the Genome Index Path. Try to find it under /Users/Buzzzuoyi/Google Drive/learn/data/hg38
root                 main    @ 07/17/21 20:45:44: Index files can not be found. Start to generate them ...
Traceback (most recent call last):
  File "/Users/Buzzzuoyi/opt/anaconda3/envs/runHiC/bin/runHiC", line 830, in <module>
    run(args, commands)
  File "/Users/Buzzzuoyi/opt/anaconda3/envs/runHiC/bin/runHiC", line 286, in run
    args.func(args, commands)
  File "/Users/Buzzzuoyi/opt/anaconda3/envs/runHiC/bin/runHiC", line 334, in mapping
    buildMapIndex(aligner, genomeFolder, genomeName)
  File "/Users/Buzzzuoyi/opt/anaconda3/envs/runHiC/lib/python3.9/site-packages/runHiC/mapping.py", line 190, in buildMapIndex
    subprocess.check_call(' '.join(build_command), shell=True)
  File "/Users/Buzzzuoyi/opt/anaconda3/envs/runHiC/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'bwa index /Users/Buzzzuoyi/Google Drive/learn/data/hg38/hg38.fa' returned non-zero exit status 1.
```

What would you suggest me to do?

Thanks in advance!

Yi

**Comment by XiaoTaoWang** [comment]
Yes, the program doesn't allow space in the file path, is it possible to change the folder name "Google Drive" (just replace the space with "_" or other characters)?

**Comment by zuoyi93** [comment]
Thanks for your prompt reply! I will try it out on a Linux virtual machine with no space in the directory. Thanks again!
